### ISSUE TITLE
哨兵2-A数据出现的问题

### ISSUE THREAD

**Issue by 644163476** [Zhaoguanhua/AtmosphericCorrection#4]
ERROR 4: `F:\huangyandao\s2\S2A_MSIL1C_20160511T024332_N0202_R046_T50PNB_20160511T024328.SAFE\GRANULE\L1C_T50PNB_A004619_20160511T024328\IMG_DATA\T50PNB_20160511T024332_B05.jp2' not recognized as a supported file format.
ERROR 4: `F:\huangyandao\s2\S2A_MSIL1C_20160511T024332_N0202_R046_T50PNB_20160511T024328.SAFE\GRANULE\L1C_T50PNB_A004619_20160511T024328\IMG_DATA\T50PNB_20160511T024332_B06.jp2' not recognized as a supported file format.
ERROR 4: `F:\huangyandao\s2\S2A_MSIL1C_20160511T024332_N0202_R046_T50PNB_20160511T024328.SAFE\GRANULE\L1C_T50PNB_A004619_20160511T024328\IMG_DATA\T50PNB_20160511T024332_B07.jp2' not recognized as a supported file format.
F:\huangyandao\s2\S2A_MSIL1C_20160511T024332_N0202_R046_T50PNB_20160511T024328.SAFE\GRANULE\L1C_T50PNB_A004619_20160511T024328\IMG_DATA\T50PNB_20160511T024332_B07.jp2数据集读取为空
F:\huangyandao\s2\S2A_MSIL1C_20160511T024332_N0202_R046_T50PNB_20160511T024328.SAFE\GRANULE\L1C_T50PNB_A004619_20160511T024328\IMG_DATA\T50PNB_20160511T024332_B08.jp2数据集读取为空

**Comment by 644163476** [comment]
还有一个基本的问题想问作者
    file_path = parse_arguments(sys.argv[1:]).Input_dir
    # 输出路径
    output_file = parse_arguments(sys.argv[2:]).Output_dir
如何导入文件啊

**Comment by Zhaoguanhua** [comment]
> ERROR 4: `F:\huangyandao\s2\S2A_MSIL1C_20160511T024332_N0202_R046_T50PNB_20160511T024328.SAFE\GRANULE\L1C_T50PNB_A004619_20160511T024328\IMG_DATA\T50PNB_20160511T024332_B05.jp2' not recognized as a supported file format. ERROR 4: `F:\huangyandao\s2\S2A_MSIL1C_20160511T024332_N0202_R046_T50PNB_20160511T024328.SAFE\GRANULE\L1C_T50PNB_A004619_20160511T024328\IMG_DATA\T50PNB_20160511T024332_B06.jp2' not recognized as a supported file format.
> ERROR 4: `F:\huangyandao\s2\S2A_MSIL1C_20160511T024332_N0202_R046_T50PNB_20160511T024328.SAFE\GRANULE\L1C_T50PNB_A004619_20160511T024328\IMG_DATA\T50PNB_20160511T024332_B07.jp2' not recognized as a supported file format.
> F:\huangyandao\s2\S2A_MSIL1C_20160511T024332_N0202_R046_T50PNB_20160511T024328.SAFE\GRANULE\L1C_T50PNB_A004619_20160511T024328\IMG_DATA\T50PNB_20160511T024332_B07.jp2数据集读取为空
> F:\huangyandao\s2\S2A_MSIL1C_20160511T024332_N0202_R046_T50PNB_20160511T024328.SAFE\GRANULE\L1C_T50PNB_A004619_20160511T024328\IMG_DATA\T50PNB_20160511T024332_B08.jp2数据集读取为空

好像是gdal版本的问题，2.0版本不支持jpg格式的数据，需要3.0以上版本。

**Comment by Zhaoguanhua** [comment]
> 还有一个基本的问题想问作者
> file_path = parse_arguments(sys.argv[1:]).Input_dir
> # 输出路径
> output_file = parse_arguments(sys.argv[2:]).Output_dir
> 如何导入文件啊
